### ISSUE TITLE
Is this the correct way to put rule in suricata 5.0 ?

### ISSUE THREAD

**Issue by arafatx** [Cyberg-ON/Timon-Rules#1]
```
cd /usr/share/suricata/rules
wget https://raw.githubusercontent.com/Cyberg-ON/Timon-Rules/master/cybergon.rules
```
is that enough ?

I have been using suricata-update tool (https://github.com/OISF/suricata-update) to update suricata official rules automatically via cron and the rules updated to /var/lib/suricata/rules. From the documentation, I read that I shouldn't put anything inside that folder. Should I use this rule together with the suricata-update tool? I mean is there any performance issue?

**Comment by cybergon-ladiesman217** [comment]
Hi!
You can use this repo with suricata-update too, like this:
suricata-update add-source https://gitlab.com/cybergon/timon-rules/raw/master/cybergon.rules cybergon/timon
Then:
suricata-update update-sources
suricata-update

**Comment by arafatx** [comment]
Ok, I never thought the source can be external link. THanks!
